### ISSUE TITLE
1.2.2. EDT

### ISSUE THREAD

**Issue by jrsosago** [jrsosago/HSP#16]
**Descripción**
Realizar la EDT del proyecto.

**Tareas a Realizar:**
- [x] Realizar EDT en Project con cronograma y asignados.
- [x] Realizar documento de la EDT.

**Comment by jrsosago** [comment]
Se realizo la EDT y se encuentra en la Rama Principal en la siguiente dirección: Gerencia del Proyecto/Gestión del Alcance del Proyecto

**Comment by jrsosago** [comment]
Se cierra está Issue temporalmente por tareas terminadas pero se puede reabrir para realizar versiones posteriores.

**Comment by KmiArthur** [comment]
## Actualización en el árbol y diagrama.
Asignado: @kmiarthur

**Comment by jrsosago** [comment]
Se cierra está Issue temporalmente por tareas terminadas pero se puede reabrir para realizar versiones posteriores.
