### ISSUE TITLE
Plantilla General de Documentos

### ISSUE THREAD

**Issue by KmiArthur** [jrsosago/HSP#29]
**Descripción**
plantilla general de documentos.

**Tareas a realizar:**
- [x] Archivo de documento para plantilla

**Comment by KmiArthur** [comment]
La plantilla fue cargada en la ruta `comercial>plantillas>Plantilla Documentos.docx`
La plantilla consta de actualizaciones automáticas. En lo posible no ajustar cambios en ella ni en documentos.

**Comment by jrsosago** [comment]
Se cambia la ruta del archivo a Gerencia del proyecto/plantillas Documentos
